// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pokemon.proto

package pokebot

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pokemon struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Height               int32    `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	Weight               int32    `protobuf:"varint,4,opt,name=weight" json:"weight,omitempty"`
	Types                []string `protobuf:"bytes,5,rep,name=types" json:"types,omitempty"`
	Thumbnail            string   `protobuf:"bytes,6,opt,name=thumbnail" json:"thumbnail,omitempty"`
	Image                string   `protobuf:"bytes,7,opt,name=image" json:"image,omitempty"`
	Habitats             string   `protobuf:"bytes,8,opt,name=habitats" json:"habitats,omitempty"`
	FlavorText           string   `protobuf:"bytes,9,opt,name=flavorText" json:"flavorText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pokemon) Reset()         { *m = Pokemon{} }
func (m *Pokemon) String() string { return proto.CompactTextString(m) }
func (*Pokemon) ProtoMessage()    {}
func (*Pokemon) Descriptor() ([]byte, []int) {
	return fileDescriptor_pokemon_3e2d32e280629a90, []int{0}
}
func (m *Pokemon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pokemon.Unmarshal(m, b)
}
func (m *Pokemon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pokemon.Marshal(b, m, deterministic)
}
func (dst *Pokemon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pokemon.Merge(dst, src)
}
func (m *Pokemon) XXX_Size() int {
	return xxx_messageInfo_Pokemon.Size(m)
}
func (m *Pokemon) XXX_DiscardUnknown() {
	xxx_messageInfo_Pokemon.DiscardUnknown(m)
}

var xxx_messageInfo_Pokemon proto.InternalMessageInfo

func (m *Pokemon) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pokemon) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pokemon) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Pokemon) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Pokemon) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *Pokemon) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

func (m *Pokemon) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Pokemon) GetHabitats() string {
	if m != nil {
		return m.Habitats
	}
	return ""
}

func (m *Pokemon) GetFlavorText() string {
	if m != nil {
		return m.FlavorText
	}
	return ""
}

type PokeInput struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PokeInput) Reset()         { *m = PokeInput{} }
func (m *PokeInput) String() string { return proto.CompactTextString(m) }
func (*PokeInput) ProtoMessage()    {}
func (*PokeInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_pokemon_3e2d32e280629a90, []int{1}
}
func (m *PokeInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PokeInput.Unmarshal(m, b)
}
func (m *PokeInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PokeInput.Marshal(b, m, deterministic)
}
func (dst *PokeInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PokeInput.Merge(dst, src)
}
func (m *PokeInput) XXX_Size() int {
	return xxx_messageInfo_PokeInput.Size(m)
}
func (m *PokeInput) XXX_DiscardUnknown() {
	xxx_messageInfo_PokeInput.DiscardUnknown(m)
}

var xxx_messageInfo_PokeInput proto.InternalMessageInfo

func (m *PokeInput) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Pokemon)(nil), "pokebot.Pokemon")
	proto.RegisterType((*PokeInput)(nil), "pokebot.PokeInput")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PokeBotClient is the client API for PokeBot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PokeBotClient interface {
	// A server-to-client streaming RPC.
	SearchPokemon(ctx context.Context, in *PokeInput, opts ...grpc.CallOption) (PokeBot_SearchPokemonClient, error)
}

type pokeBotClient struct {
	cc *grpc.ClientConn
}

func NewPokeBotClient(cc *grpc.ClientConn) PokeBotClient {
	return &pokeBotClient{cc}
}

func (c *pokeBotClient) SearchPokemon(ctx context.Context, in *PokeInput, opts ...grpc.CallOption) (PokeBot_SearchPokemonClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PokeBot_serviceDesc.Streams[0], "/pokebot.PokeBot/searchPokemon", opts...)
	if err != nil {
		return nil, err
	}
	x := &pokeBotSearchPokemonClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PokeBot_SearchPokemonClient interface {
	Recv() (*Pokemon, error)
	grpc.ClientStream
}

type pokeBotSearchPokemonClient struct {
	grpc.ClientStream
}

func (x *pokeBotSearchPokemonClient) Recv() (*Pokemon, error) {
	m := new(Pokemon)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PokeBotServer is the server API for PokeBot service.
type PokeBotServer interface {
	// A server-to-client streaming RPC.
	SearchPokemon(*PokeInput, PokeBot_SearchPokemonServer) error
}

func RegisterPokeBotServer(s *grpc.Server, srv PokeBotServer) {
	s.RegisterService(&_PokeBot_serviceDesc, srv)
}

func _PokeBot_SearchPokemon_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PokeInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PokeBotServer).SearchPokemon(m, &pokeBotSearchPokemonServer{stream})
}

type PokeBot_SearchPokemonServer interface {
	Send(*Pokemon) error
	grpc.ServerStream
}

type pokeBotSearchPokemonServer struct {
	grpc.ServerStream
}

func (x *pokeBotSearchPokemonServer) Send(m *Pokemon) error {
	return x.ServerStream.SendMsg(m)
}

var _PokeBot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pokebot.PokeBot",
	HandlerType: (*PokeBotServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "searchPokemon",
			Handler:       _PokeBot_SearchPokemon_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pokemon.proto",
}

func init() { proto.RegisterFile("pokemon.proto", fileDescriptor_pokemon_3e2d32e280629a90) }

var fileDescriptor_pokemon_3e2d32e280629a90 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xdd, 0x4a, 0x84, 0x40,
	0x14, 0xc7, 0x1b, 0xd7, 0x8f, 0xf5, 0xd0, 0x46, 0x1c, 0x22, 0x86, 0x25, 0x4a, 0xbc, 0x12, 0x02,
	0x89, 0xba, 0xea, 0x56, 0xea, 0x22, 0xba, 0x48, 0xa4, 0x17, 0x18, 0xdb, 0x69, 0x1d, 0x5a, 0x1d,
	0xd1, 0xb3, 0x7d, 0xbc, 0x4e, 0xaf, 0xd6, 0x8b, 0x84, 0x33, 0xe6, 0xb6, 0x77, 0xfe, 0x7e, 0xff,
	0xe3, 0x81, 0xf3, 0x1f, 0x58, 0xb4, 0xfa, 0x4d, 0xd6, 0xba, 0x49, 0xdb, 0x4e, 0x93, 0xc6, 0x60,
	0xc0, 0x52, 0x53, 0xfc, 0xc3, 0x20, 0xc8, 0x6d, 0x84, 0x47, 0xe0, 0xa8, 0x15, 0x67, 0x11, 0x4b,
	0xbc, 0xc2, 0x51, 0x2b, 0x44, 0x70, 0x1b, 0x51, 0x4b, 0xee, 0x44, 0x2c, 0x09, 0x0b, 0xf3, 0x8d,
	0xa7, 0xe0, 0x57, 0x52, 0xad, 0x2b, 0xe2, 0x33, 0x33, 0x37, 0xd2, 0xe0, 0x3f, 0xac, 0x77, 0xad,
	0xb7, 0x84, 0x27, 0xe0, 0xd1, 0x57, 0x2b, 0x7b, 0xee, 0x45, 0xb3, 0x24, 0x2c, 0x2c, 0xe0, 0x19,
	0x84, 0x54, 0x6d, 0xeb, 0xb2, 0x11, 0x6a, 0xc3, 0x7d, 0xb3, 0x7e, 0x27, 0x86, 0x7f, 0x54, 0x2d,
	0xd6, 0x92, 0x07, 0x26, 0xb1, 0x80, 0x4b, 0x98, 0x57, 0xa2, 0x54, 0x24, 0xa8, 0xe7, 0x73, 0x13,
	0x4c, 0x8c, 0xe7, 0x00, 0xaf, 0x1b, 0xf1, 0xae, 0xbb, 0x67, 0xf9, 0x49, 0x3c, 0x34, 0xe9, 0x3f,
	0x13, 0x5f, 0x40, 0x38, 0x1c, 0xf9, 0xd0, 0xb4, 0x5b, 0x9a, 0xce, 0x62, 0xbb, 0xb3, 0xae, 0xef,
	0x6c, 0x0b, 0x99, 0x26, 0xbc, 0x85, 0x45, 0x2f, 0x45, 0xf7, 0x52, 0xfd, 0xd5, 0x82, 0xe9, 0x58,
	0x56, 0x3a, 0xed, 0x58, 0x1e, 0xef, 0xb9, 0x5a, 0x37, 0xf1, 0xc1, 0x15, 0xcb, 0x2e, 0x01, 0x95,
	0x4e, 0xa7, 0xa6, 0xed, 0x44, 0x76, 0x38, 0x6e, 0xce, 0x87, 0xe6, 0x73, 0xf6, 0xed, 0xb8, 0xf9,
	0xd3, 0xe3, 0x7d, 0xe9, 0x9b, 0x97, 0xb8, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x43, 0x54, 0x8f,
	0xee, 0x9a, 0x01, 0x00, 0x00,
}
